#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Command {
    MoveLeft { extend: bool },
    MoveRight { extend: bool },
    MoveUp { extend: bool },
    MoveDown { extend: bool },
    MoveLineStart { extend: bool },
    MoveLineEnd { extend: bool },
    MoveDocumentStart { extend: bool },
    MoveDocumentEnd { extend: bool },
    MoveWordLeft { extend: bool },
    MoveWordRight { extend: bool },
    PageUp { extend: bool },
    PageDown { extend: bool },
    Save,
    SaveAs,
    Quit,
    Undo,
    Redo,
    OpenSearch,
    SearchNext,
    SearchPrevious,
    OpenCommandBar,
    DeleteToEndOfLine,
    DeleteWordBackward,
    CopySelection,
    CutSelection,
    Paste,
    ToggleExplorer,
    OpenFilePicker,
    OpenBufferPicker,
    NextBuffer,
    PreviousBuffer,
    SplitVertical,
    SplitHorizontal,
    FocusNextPane,
    ResizePaneLeft,
    ResizePaneRight,
    ReloadChangedFiles,
}
